<<<<<<< HEAD
"""
Django settings for django_architecture_design project.

Generated by 'django-admin startproject' using Django 2.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""

import os
=======
>>>>>>> e529b3c6abe7feb9855854a3345b72bbc24a3bde
from .base import *

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ['*']

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

<<<<<<< HEAD
=======
# Database
# https://docs.djangoproject.com/en/2.1/ref/settings/#databases

>>>>>>> e529b3c6abe7feb9855854a3345b72bbc24a3bde
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
<<<<<<< HEAD
}
=======
}
>>>>>>> e529b3c6abe7feb9855854a3345b72bbc24a3bde
